- name: Instalar segurança básica (UFW, Fail2ban, updates, auditd)
  ansible.builtin.apt:
    name: [ufw, fail2ban, unattended-upgrades, auditd]
    state: present
    update_cache: yes
  tags: [seguranca, pacotes]

- name: Permitir SSH no UFW
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp
  tags: [seguranca, ufw]

- name: Abrir portas adicionais (se definidas)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allow_tcp | default([]) }}"
  tags: [seguranca, ufw]

- name: Ativar UFW (política deny por omissão)
  community.general.ufw:
    state: enabled
    policy: deny
  tags: [seguranca, ufw]

- name: Configurar unattended-upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
    content: |
      Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
        "${distro_id}ESMApps:${distro_codename}";
        "${distro_id}ESM:${distro_codename}";
      };
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "true";
  tags: [seguranca, updates]

- name: Garantir serviços ativos (fail2ban, updates, auditd)
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: [fail2ban, unattended-upgrades, auditd]
  tags: [seguranca]
