- name: Instalar rsync
  ansible.builtin.apt:
    name: rsync
    state: present
    update_cache: yes
  tags: [backup]

- name: Script de backup para servidor central
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /usr/local/bin/isptec-backup.sh
    mode: "0750"
  tags: [backup]

- name: Agendar cron de backup diário
  ansible.builtin.cron:
    name: "isptec backup"
    user: root
    minute: "{{ backup_schedule.split()[0] }}"
    hour:   "{{ backup_schedule.split()[1] }}"
    day:    "{{ backup_schedule.split()[2] }}"
    month:  "{{ backup_schedule.split()[3] }}"
    weekday:"{{ backup_schedule.split()[4] }}"
    job: "/usr/local/bin/isptec-backup.sh"
  tags: [backup, cron]
