- name: Baseline do node
  hosts: desktop
  become: true

  tasks:
    - name: Atualizar pacotes apt
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar utilitários básicos
      apt:
        name:
          - curl
          - vim
          - net-tools
          - htop
        state: present

    - name: Garantir que IPv4 é preferido
      lineinfile:
        path: /etc/gai.conf
        regexp: '^#?precedence ::ffff:0:0/96'
        line: 'precedence ::ffff:0:0/96  100'
        state: present
      notify: Restart networking

    - name: Ativar sincronização de tempo
      service:
        name: systemd-timesyncd
        state: started
        enabled: yes

  handlers:
    - name: Restart networking
      service:
        name: systemd-networkd
        state: restarted
